name: Node.js CI/CD (Windows Server)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    steps:
      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@v5.0.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.WINDOWS_SSH_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.WINDOWS_HOST }}
          REMOTE_USER: ${{ secrets.WINDOWS_USER }}
          TARGET: "C:/apps/my-node-app"
